const events = {
    APP_READY: 'APP_READY',
    START_LOADING: 'START_LOADING',
    END_LOADING: 'END_LOADING',
    ALERT_MESSAGE: 'ALERT_MESSAGE',
    DISMISS_MESSAGE: 'DISMISS_MESSAGE',
    CLEAR_MESSAGES: 'CLEAR_MESSAGES',
    SHOW_TWO_FACTOR: 'SHOW_TWO_FACTOR',
    CLEAR_TWO_FACTORS: 'CLEAR_TWO_FACTORS',
    REMOVE_TWO_FACTOR: 'REMOVE_TWO_FACTOR'
};

export default events;
